// <auto-generated />
using BackendAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BackendAPI.Migrations
{
    [DbContext(typeof(BackendContext))]
    [Migration("20220815201736_SeedingDB")]
    partial class SeedingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BackendAPI.Models.Script", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("lang")
                        .HasColumnType("text");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.Property<string>("scriptName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Scripts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            lang = "python",
                            path = "test.py",
                            scriptName = "test.py"
                        },
                        new
                        {
                            ID = 2,
                            lang = "ruby",
                            path = "test.rb",
                            scriptName = "test.rb"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
